# Copyright (c) 2023, Tridz Technologies Pvt. Ltd. and contributors
# For license information, please see license.txt

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import flt


class URYMenu(Document):
    def validate(self):
        for d in self.items:
            if not d.rate:
                d.rate = frappe.db.get_value("Item", d.item, "standard_rate")

    def on_update(self):
        """Sync Price List"""
        self.make_price_list()

    def on_trash(self):
        """clear prices"""
        self.clear_item_price()

    def clear_item_price(self, price_list=None):
        """clear all item prices for this menu"""
        if not price_list:
            price_list = self.get_price_list().name
        frappe.db.sql("delete from `tabItem Price` where price_list = %s", price_list)

    def make_price_list(self):
        # create price list for menu
        price_list = self.get_price_list()
        self.db_set("price_list", price_list.name)

        # delete old items
        self.clear_item_price(price_list.name)

        for d in self.items:
            # Always stamp uom = item.stock_uom. Without a uom on the Item
            # Price, ERPNext's standard POS Invoice validation can't match
            # this price row during save and falls through to
            # insert_item_price() which creates a duplicate and fires a
            # noisy "Item Price added for <a>…</a>" alert on every order.
            # See CLAUDE.md "Fixes log" 2026-04-08.
            stock_uom = frappe.db.get_value("Item", d.item, "stock_uom")
            frappe.get_doc(
                dict(
                    doctype="Item Price",
                    price_list=price_list.name,
                    item_code=d.item,
                    price_list_rate=d.rate,
                    uom=stock_uom,
                )
            ).insert()

    def get_price_list(self):
        """Create price list for menu if missing"""
        price_list_name = frappe.db.get_value(
            "Price List", dict(restaurant_menu=self.name)
        )
        if price_list_name:
            price_list = frappe.get_doc("Price List", price_list_name)
        else:
            price_list = frappe.new_doc("Price List")
            price_list.restaurant_menu = self.name
            price_list.price_list_name = self.name

        price_list.enabled = 1
        price_list.selling = 1
        price_list.save()

        return price_list


def _find_menu_item_row(items, item):
    """Return the menu's items-table row for `item`, or None. Pure (no DB)."""
    for d in items:
        if getattr(d, "item", None) == item:
            return d
    return None


def _pick_menu_item_rate(explicit_rate, standard_rate):
    """Pure rate-precedence resolver for an item added to a menu.

    Precedence: explicit rate typed in the dialog > the Item's standard_rate > 0.
    `None`/`""` count as 'unset'; an explicit 0 is a real price and wins. Kept pure
    (no DB) so the precedence logic can be unit-tested directly.
    """
    for candidate in (explicit_rate, standard_rate):
        if candidate not in (None, ""):
            return flt(candidate)
    return 0.0


def _diff_menu_item(existing_rate, existing_course, new_rate, new_course):
    """Return a list of {field, old, new} changes between an item's existing menu
    row and the proposed rate/course. Empty list == no change. Pure (no DB)."""
    changes = []
    if flt(existing_rate) != flt(new_rate):
        changes.append({"field": "Rate", "old": flt(existing_rate), "new": flt(new_rate)})
    if (existing_course or None) != (new_course or None):
        changes.append(
            {"field": "Course", "old": existing_course or "", "new": new_course or ""}
        )
    return changes


@frappe.whitelist()
def get_menu_item_details(menu, item):
    """For the Item form dialog: the item's current row on `menu`, if present.

    Lets the dialog pre-fill the rate/course and tell the user the item is already
    on the menu before they hit Create.
    """
    row = frappe.db.get_value(
        "URY Menu Item",
        {"parent": menu, "parenttype": "URY Menu", "item": item},
        ["rate", "course"],
        as_dict=True,
    )
    if not row:
        return {"exists": False}
    return {"exists": True, "rate": row.rate, "course": row.course}


@frappe.whitelist()
def add_item_to_menu(item, menu, course=None, rate=None, confirm_update=0):
    """Add an Item to a URY Menu from the Item form's "Add to ExPOS Menu" button.

    The rate goes into the menu's OWN price list (regenerated by make_price_list on
    save). If the item is already on the menu, the change is NOT applied silently:
      - no rate/course difference          -> {"action": "unchanged"}
      - a difference, no confirmation       -> {"action": "needs_confirmation", "changes": [...]}
      - a difference, confirm_update=1      -> applies it, {"action": "updated", "changes": [...]}
    A brand-new item returns {"action": "added"}.
    """
    confirm_update = int(confirm_update or 0)

    if not frappe.db.exists("Item", item):
        frappe.throw(_("Item {0} not found").format(item))

    menu_doc = frappe.get_doc("URY Menu", menu)
    existing = _find_menu_item_row(menu_doc.items, item)

    standard_rate = frappe.db.get_value("Item", item, "standard_rate")
    new_rate = _pick_menu_item_rate(rate, standard_rate)
    new_course = course or None

    if existing is None:
        menu_doc.append(
            "items",
            {
                "item": item,
                "item_name": frappe.db.get_value("Item", item, "item_name"),
                "rate": new_rate,
                "course": new_course,
            },
        )
        menu_doc.save()
        return {"action": "added", "rate": new_rate, "course": new_course}

    changes = _diff_menu_item(existing.rate, existing.course, new_rate, new_course)
    if not changes:
        return {"action": "unchanged"}
    if not confirm_update:
        return {"action": "needs_confirmation", "changes": changes}

    existing.rate = new_rate
    existing.course = new_course
    menu_doc.save()
    return {"action": "updated", "changes": changes}
